class Essbase

    module Loads

        # Map of Essbase load error codes to error messages
        DATA_LOAD_ERROR_CODES = {
            3301 => 'Member %s in bad col for dimension',
            3302 => 'Member %s in bad col for generation',
            3303 => 'Member %s not found in database',
            3304 => 'Insufficient access to store data',
            3305 => 'Incorrect syntax for member %s',
            3306 => 'Alias %s already in use',
            3307 => 'Different parent for member %s',
            3331 => 'No parent for child member %s',
            3308 => 'Different dimension for member %s',
            3309 => 'Level zero required',
            3310 => 'Level zero required',
            3311 => 'Member required',
            3312 => 'Member required',
            3313 => 'Member required',
            3314 => 'Alias name is member name',
            3315 => 'Change Attribute = FALSE',
            3316 => 'Change Formula = FALSE',
            3317 => 'Error adding member %s',
            3318 => 'Error moving member %s',
            3319 => 'Error adding alias %s',
            3320 => 'Error adding attribute %s',
            3321 => 'Error adding user attribute %s',
            3322 => 'Error adding formula %s',
            3323 => 'Error adding currency name %s',
            3324 => 'Error adding currency category %s',
            3325 => 'Column Ignored - error in header',
            3326 => 'Match Mbr # or P/C required',
            3327 => 'Country Dim Type required',
            3328 => 'Account Dim Type required',
            3329 => 'Illegal Member/Parent Combination',
            3330 => 'Different generation for member %s',
            3331 => 'Child Member %s with no parent',
            3332 => 'Member name %s used in record as alias',
            3333 => 'Bad data value supplied: %s',
            3334 => 'Record rejected because of null columns',
            3335 => 'Record rejected because of duplicate member names',
            3336 => 'Member/Data %s Unknown',
            3337 => 'Record rejected because of dimension conflicts with Header Name: %s',
            3338 => 'Cannot load data to imply shared member with no real child',
            3339 => 'Cannot uniquely identify a member with the name %s',
            3340 => 'Member name %s must be unique among its siblings',
            3341 => 'Error adding member indentifer to member %s',
            3342 => 'Member name %s must be unique in the dimension',
            3343 => 'Member name %s can not be the same as dimension name',
            3344 => 'Member name %s can not be duplicate at the generatoin in the dimension',
            3345 => 'Error setting member id %s',
            3346 => 'Error deleting member id %s',
            3347 => 'Error deleting user attribute %s',
            3348 => 'Error deleting user attribute %s',
            3349 => 'Error deleting formula %s',
            3350 => 'Error deleting alias %s',
            3351 => 'Error deleting currency name %s',
            3352 => 'Error deleting currency category %s',
            3353 => 'Error adding member %s, all parents unspecified',
            3354 => 'Error adding shared member %s',
            3355 => 'Error finding refmember %s',
            3356 => 'Error adding attribute member %s for a numerical range',
            3360 => 'Missing base dimension member %s',
            3361 => 'Attribute parent/child combo not found',
            3362 => 'Internal transaction error',
            3363 => 'Data cannot be converted to numeric mbr: %s',
            3364 => 'Attrdim field required following Attrparent',
            3365 => 'Member required',
            3366 => 'Error seting solve order',
            3367 => 'Change Formula = FALSE',
            3368 => 'Only ASO allows solver order',
            3369 => 'Duplicate member %s data in dataload',
            3370 => 'Member required',
            3371 => 'Error seting solve order',
            3372 => 'Change Formula = FALSE',
            3373 => 'Only ASO allows solver order',
            3374 => 'Duplicate occurrences of an attribute member %s cannot be resolved.',
            3375 => 'Error Adding Member Comment %s',
            3376 => 'Error Deleting Member Comment %s',
            3377 => 'Error Adding extended Member Comment %s',
            3378 => 'Error Deleting extended Member Comment %s',
            3379 => 'Bad text measure value supplied: %s',
            3380 => 'Invalid member combination for storing smartlist',
            3381 => 'Invalid member combination for %s',
            3382 => 'Error setting smartlist to member %s',
            3383 => "Can't save smartlist %s",
            3384 => "Can't convert smartlist id to a number: %s",
            3385 => 'Illegal smartlist text: %s',
            3386 => 'Duplicate smartlist text: %s',
            3387 => 'Duplicate smartlist id: %s',
            3388 => 'Discrete end independent member must be the same as the start independent member: %s',
            3375 => 'Error Adding Member Format String: %s',
            3376 => 'Error Deleting Member Format String: %s',
            3389 => 'Bad date type measure value supplied: %s'
        }

    end

end

